students=["babita","jethalal","shivukumar"]
print(students)
print(students[0])
print(students[-1])
print(students[-3:-1])
students.append("iyer")
students.insert(1,"daya")
students.remove("shivukumar")
print(students)
students.sort()
print(students)
students.reverse()
print(students)
print(len(students))
#tuple
course=("python fullstack developer",3,12500,12500)
print(course[1])
print(course[-1])
print(course[0:2])
print(course.count(12500))
print(course.index(3))
print(course)
cou=list(course)
cou.pop()
course=tuple(cou)
print(course)
#dictionary
employees={
    1001:"roxy",1002:"bajaj",1003:"shivu"
}
print(employees)
print(employees[1002])
print(employees.keys())
print(employees.values())
employees[1005]="jayalaxmi"
employees[1001]="rhoit"
employees[1005]="tandem"
print(employees)
print(len(employees))

